<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
	<dict>
		<key>items</key>
		<array>
			<dict>
				<key>assets</key>
				<array>
					<dict>
						<key>kind</key>
						<string>software-package</string>
						<key>url</key>
						<string>https://www.itunesappstore.cn/ioshelper/dl.php?s=b92ca76a-223f-11e9-a70a-00163e0e27d5</string>
					</dict>
					<dict>
						<key>kind</key>
						<string>display-image</string>
						<key>url</key>
						<string>https://www.itunesappstore.cn/ioshelper/../files//15478805351196899546-2048.png</string>
					</dict>
					<dict>
						<key>kind</key>
						<string>full-size-image</string>
						<key>url</key>
						<string>https://www.itunesappstore.cn/ioshelper/../files//15478805351196899546-2048.png</string>
					</dict>
				</array>
				<key>metadata</key>
				<dict>
					<key>bundle-identifier</key>
					<string>com.kehr.androstenediol</string>
					<key>bundle-version</key>
					<string>1.0.0.101</string>
					<key>kind</key>
					<string>software</string>
					<key>title</key>
					<string>2048</string>
				</dict>
			</dict>
		</array>
	</dict>
</plist>